version: "3.8"
services:
  server:
    image: tensorflow/serving
    volumes:
      - ./saved_models:/saved_models/1602624873
    ports:
      - '8501:8501'
    environment:
        MODEL_NAME: 1602624873
        MODEL_BASE_PATH: /saved_models/

  web:
    image: flaskweb2
    build:
        context: ./flask_app
        dockerfile: Dockerfile.dev
    ports:
      - '8080:8080'