apiVersion: apps/v1
kind: Deployment
metadata:
  name: tf-kube-dev
spec:
  replicas: 3
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name: server
          image: steveoni/tfupdate:1.1
          ports:
            - containerPort: 8501
          env:
            - name: MODEL_NAME
              value: "1602624873"
            - name: MODEL_BASE_PATH
              value: /saved_models/