apiVersion: apps/v1
kind: Deployment
metadata:
  name: tfweb-dev
spec:
  replicas: 3
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: web
          image: steveoni/tfweb:1.0
          ports:
            - containerPort: 8080